dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: raspberrypicentos8
    image: registry.gitlab.com/dvonessen/docker-molecule-nonroot/centos:8-systemd
    pre_build_image: true
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: "/usr/lib/systemd/systemd"
  - name: raspberrypidebian10
    image: registry.gitlab.com/dvonessen/docker-molecule-nonroot/debian:10-systemd
    pre_build_image: true
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: "/lib/systemd/systemd"
  - name: raspberrypiubuntu2004
    image: registry.gitlab.com/dvonessen/docker-molecule-nonroot/ubuntu:20.04-systemd
    pre_build_image: true
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: "/lib/systemd/systemd"
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      interpreter_python: auto_silent
lint: |
  set -e
  yamllint -c .yamllint .
  flake8
  ansible-lint
